name: Laravel CI/CD
on:
  push:
    branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Install Composer
#        uses: php-actions/composer@v2
#        with:
#          args: install --no-dev

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Tests
        run: php artisan test

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOSTINGER_SSH_IP }}
          username: ${{ secrets.HOSTINGER_SSH_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY_ED25519 }}
          script: |
            cd ${{ secrets.HOSTINGER_BARCODE_DIRECTORY }}
            git pull origin main
            composer install --no-dev            
            php artisan optimize:clear
